# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-03-09 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='\u6807\u9898')),
                ('url', models.CharField(max_length=120, verbose_name='\u542b\u6b63\u5219\u7684URL')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='\u89d2\u8272\u540d\u79f0')),
                ('permissions', models.ManyToManyField(blank=True, to='rbac.Permission', verbose_name='\u62e5\u6709\u6240\u6709\u6743\u9650')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='\u7528\u6237\u540d')),
                ('password', models.CharField(max_length=64, verbose_name='\u5bc6\u7801')),
                ('email', models.CharField(max_length=32, verbose_name='\u90ae\u7bb1')),
                ('roles', models.ManyToManyField(blank=True, to='rbac.Role', verbose_name='\u62e5\u6709\u7684\u6240\u6709\u89d2\u8272')),
            ],
        ),
    ]
