# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-03-09 05:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flavor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=12)),
                ('memory', models.IntegerField()),
                ('vcpu', models.IntegerField()),
                ('disk', models.IntegerField()),
            ],
        ),
    ]
