#!/bin/sh
#
# webvirtmgr-console  WebVirtMgr Console noVNC Proxy
#
# chkconfig:   - 98 02
# description: WebVirtMgr Console noVCN Proxy Server

### BEGIN INIT INFO
# Provides:
# Required-Start: $remote_fs $network $syslog
# Required-Stop: $remote_fs $syslog
# Default-Stop: 0 1 6
# Short-Description: WebVirtMgr Console noVNC Proxy
# Description: WebVirtMgr Console noVNC Proxy Server
### END INIT INFO

. /etc/rc.d/init.d/functions

prog="webvirtmgr-console"
exec="/var/www/webvirtmgr/console/$prog"
lockfile="/var/lock/subsys/$prog"
pidfile="/var/run/webvirtmgr/$prog.pid"
logfile="/var/log/$prog.log"
username="nginx"

# load webvirtmgr-console preferences
if [ -f /etc/sysconfig/webvirtmgr-console ]; then
    . /etc/sysconfig/webvirtmgr-console
fi

if [ ! -d /var/run/webvirtmgr ]; then
        mkdir /var/run/webvirtmgr
        chown $username /var/run/webvirtmgr
fi

start() {
    [ -x $exec ] || exit 5

    echo -n $"Starting $prog: "
    export PYTHONPATH=$PYTHONPATH:/usr/lib/python2.6/site-packages/Django-1.5.6-py2.6.egg
    daemon --user $username --pidfile $pidfile "$exec &>/dev/null & echo \$! > $pidfile"
    retval=$?
    echo
    [ $retval -eq 0 ] && touch $lockfile
    return $retval
}

stop() {
    echo -n $"Stopping $prog: "
    killproc -p $pidfile $exec
    retval=$?
    echo
    [ $retval -eq 0 ] && rm -f $lockfile
    return $retval
}

restart() {
    stop
    start
}

reload() {
    restart
}

force_reload() {
    restart
}

rh_status() {
    status -p $pidfile $prog
}

rh_status_q() {
    rh_status >/dev/null 2>&1
}


case "$1" in
    start)
        rh_status_q && exit 0
        $1
        ;;
    stop)
        rh_status_q || exit 0
        $1
        ;;
    restart)
        $1
        ;;
    reload)
        rh_status_q || exit 7
        $1
        ;;
    force-reload)
        force_reload
        ;;
    status)
        rh_status
        ;;
    condrestart|try-restart)
        rh_status_q || exit 0
        restart
        ;;
    *)
        echo $"Usage: $0 {start|stop|status|restart|condrestart|try-restart|reload|force-reload}"
        exit 2
esac
exit $?
